version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - MYSQL_PASS=password
    networks:
      - sandbox_net

  juiceshop:
    image: bkimminich/juice-shop
    ports:
      - "8082:3000"
    restart: unless-stopped
    networks:
      - sandbox_net

networks:
  sandbox_net:
    driver: bridge
